In [1]:
import numpy as np 
a=np.array((1,2,3,4))
list_a=[1,2,3,4]
b=np.array(list_a)

print(a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [2]:
import numpy as np 

A=np.array([[1,2,3],[10,20,30]])
print(A)

[[ 1  2  3]
 [10 20 30]]


In [7]:
import numpy as np
A=np.zeros((2,3))
B=np.ones((3,5),dtype=int)

print(A)
print(B)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [9]:
import numpy as np
C=np.full((3,5),7,dtype=int)
print(C)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [13]:
import numpy as np 

np.arange(10)
np.arange(90,100)
np.arange(1,100,10)
np.arange(100,1000,50,dtype=float)

array([100., 150., 200., 250., 300., 350., 400., 450., 500., 550., 600.,
       650., 700., 750., 800., 850., 900., 950.])

In [14]:
import numpy as np 
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [15]:
import numpy as np 
np.linspace(1,100,70,dtype=int)

array([  1,   2,   3,   5,   6,   8,   9,  11,  12,  13,  15,  16,  18,
        19,  21,  22,  23,  25,  26,  28,  29,  31,  32,  34,  35,  36,
        38,  39,  41,  42,  44,  45,  46,  48,  49,  51,  52,  54,  55,
        56,  58,  59,  61,  62,  64,  65,  67,  68,  69,  71,  72,  74,
        75,  77,  78,  79,  81,  82,  84,  85,  87,  88,  89,  91,  92,
        94,  95,  97,  98, 100])

In [18]:
import numpy as np 
np.eye(5,5,0,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
import numpy as np 
A=np.empty((4,4),dtype=int)
print(A)

[[         0          0          0          0]
 [         0          0          0          0]
 [         0          0       1216          0]
 [         0 1344302964          0 1850286190]]


In [27]:
import numpy as np 
from numpy import random as rd

a=rd.randint(100)
print(a)

35


In [28]:
import numpy as np 
a=np.random.randint(100)
print(a)

93


In [30]:
import numpy as np 
from numpy import random as rd

B=rd.rand(10,3,3)
print(B)

[[[0.14215076 0.15818571 0.31278327]
  [0.41690795 0.63629078 0.69723831]
  [0.67289782 0.94056394 0.85165832]]

 [[0.76982643 0.3379841  0.76055672]
  [0.20386174 0.30972378 0.89344878]
  [0.47033143 0.04700459 0.71661438]]

 [[0.81313045 0.9671866  0.57537915]
  [0.03217391 0.40726866 0.66664959]
  [0.96190287 0.49904826 0.44872144]]

 [[0.28320284 0.8483572  0.74698368]
  [0.16103175 0.3104747  0.18026133]
  [0.20417932 0.59056456 0.19493907]]

 [[0.82989037 0.2790851  0.18158378]
  [0.12947488 0.94119868 0.95011547]
  [0.57590255 0.04980672 0.16142571]]

 [[0.02337191 0.57423338 0.58574619]
  [0.13924851 0.0139994  0.52466009]
  [0.36523771 0.66877914 0.71111823]]

 [[0.03994273 0.25480845 0.4997578 ]
  [0.11805491 0.6622038  0.82441517]
  [0.0627542  0.16397897 0.07232746]]

 [[0.24656082 0.02868442 0.98983719]
  [0.16709532 0.32407421 0.20588342]
  [0.39813986 0.5141508  0.20092399]]

 [[0.22136476 0.14463229 0.5962049 ]
  [0.55486749 0.77069306 0.79476474]
  [0.20234018 0.559915

In [31]:
import numpy as np 
from numpy import random as rd

a=rd.randint(100,size=(10,3,3))
print(a)

[[[34 98 28]
  [37 56 66]
  [29 64 82]]

 [[87 11 31]
  [81 91 20]
  [83 28 73]]

 [[ 5 16 17]
  [15 36 52]
  [99 18 40]]

 [[ 2  0 61]
  [ 5 62 14]
  [74 22 47]]

 [[ 2 71 52]
  [39  9 64]
  [55 93 61]]

 [[45 11  4]
  [84 75 73]
  [81 52 27]]

 [[55  1 58]
  [86 40 94]
  [65 68 90]]

 [[81 27 66]
  [41 25 27]
  [30 67 10]]

 [[55 67 94]
  [23 21  3]
  [74 25 69]]

 [[18  6 41]
  [28 81 80]
  [58  0 39]]]


In [33]:
import numpy as np 
from numpy import random as rd

A=rd.choice(rd.randint(100),size=(5,5))
print(A)

[[ 5  9 26 53 23]
 [79 72 66 20  6]
 [49 49  1 61 21]
 [49 20 41  1 12]
 [33 44 76 55 70]]


In [34]:
import numpy as np 
from numpy import random as rd

B=rd.choice([1,3,5,7,9],p=[0.2,0.15,0.30,0.1,0.25],size=(5,5))
print(B)

[[5 7 9 3 3]
 [7 3 7 1 9]
 [3 1 5 3 5]
 [5 7 9 9 9]
 [1 1 1 3 3]]


In [35]:
import numpy as np 
from numpy import random as rd

a=np.arange(1,100,2,dtype=int)
rd.shuffle(a)
print(a)

[67 33 23 51 41 97 83 39  7 55 53 49 73 17 15 47 35 43 21 45 99 57 91 31
 93 87 61 59 89 79 77 13  3  5 81 29  1 95 75 11 63 25 27 65 69 85 71 37
  9 19]


In [38]:
import numpy as np 
from numpy import random as rd

a=np.arange(0,50,2,dtype=int)
b=rd.permutation(a)
print(a)
print(b)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
[36  2 24 20  0 18 46 48 34 40 30 44 22 14 16 26 12  8 32  6 28 38  4 42
 10]


In [5]:
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=a*b
"""
for i in range (len(a)):
    c.append(a[i]*b[i])
"""
print(c)

[ 6 14 24 36 50]


In [6]:
import numpy as np

b=np.array([6,7,8,9,10])
"""
for i in range (len(a)):
    c.append(np.power(a[i],b[i]))
"""
print(a**b)

[      1     128    6561  262144 9765625]


In [7]:
import numpy as np

a=[1,2,3,4,5]
b=[6,7,8,9,10]
c=[]
for i in range (len(a)):
    c.append(a[i]*b[i])
print(c)

[6, 14, 24, 36, 50]


In [11]:
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([2])

print(a**b)
print(b)

[ 1  4  9 16 25]
[2]


In [19]:
import numpy as np
a=np.arange(50).reshape(5,10)
#print(a)
b=np.arange(1,6).reshape(5,1)
#print(b)
c=a*b
print(c)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 20  22  24  26  28  30  32  34  36  38]
 [ 60  63  66  69  72  75  78  81  84  87]
 [120 124 128 132 136 140 144 148 152 156]
 [200 205 210 215 220 225 230 235 240 245]]


In [23]:
import numpy as np
a=np.arange(100).reshape(5,10,2)
#print(a)
b=np.arange(5).reshape(5,1,1)
#print(b)
c=a*b
print(c)

[[[  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]
  [  0   0]]

 [[ 20  21]
  [ 22  23]
  [ 24  25]
  [ 26  27]
  [ 28  29]
  [ 30  31]
  [ 32  33]
  [ 34  35]
  [ 36  37]
  [ 38  39]]

 [[ 80  82]
  [ 84  86]
  [ 88  90]
  [ 92  94]
  [ 96  98]
  [100 102]
  [104 106]
  [108 110]
  [112 114]
  [116 118]]

 [[180 183]
  [186 189]
  [192 195]
  [198 201]
  [204 207]
  [210 213]
  [216 219]
  [222 225]
  [228 231]
  [234 237]]

 [[320 324]
  [328 332]
  [336 340]
  [344 348]
  [352 356]
  [360 364]
  [368 372]
  [376 380]
  [384 388]
  [392 396]]]


In [28]:
import numpy as np
a=np.arange(50).reshape(5,5,2)
#print(a)
b=np.arange(10).reshape(5,2)
#print(b)
c=a*b
print(c)

[[[  0   1]
  [  4   9]
  [ 16  25]
  [ 36  49]
  [ 64  81]]

 [[  0  11]
  [ 24  39]
  [ 56  75]
  [ 96 119]
  [144 171]]

 [[  0  21]
  [ 44  69]
  [ 96 125]
  [156 189]
  [224 261]]

 [[  0  31]
  [ 64  99]
  [136 175]
  [216 259]
  [304 351]]

 [[  0  41]
  [ 84 129]
  [176 225]
  [276 329]
  [384 441]]]


In [1]:
import numpy as np
a=np.arange(50).reshape(5,5,2)
b=np.arange(5).reshape(5,1)
c=a*b
print(c)

[[[  0   0]
  [  2   3]
  [  8  10]
  [ 18  21]
  [ 32  36]]

 [[  0   0]
  [ 12  13]
  [ 28  30]
  [ 48  51]
  [ 72  76]]

 [[  0   0]
  [ 22  23]
  [ 48  50]
  [ 78  81]
  [112 116]]

 [[  0   0]
  [ 32  33]
  [ 68  70]
  [108 111]
  [152 156]]

 [[  0   0]
  [ 42  43]
  [ 88  90]
  [138 141]
  [192 196]]]


In [3]:
import numpy as np
a=np.arange(25).reshape(1,5,5)
b=np.arange(5).reshape(5,1,1)
print(a*b)

[[[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[ 0  3  6  9 12]
  [15 18 21 24 27]
  [30 33 36 39 42]
  [45 48 51 54 57]
  [60 63 66 69 72]]

 [[ 0  4  8 12 16]
  [20 24 28 32 36]
  [40 44 48 52 56]
  [60 64 68 72 76]
  [80 84 88 92 96]]]


In [3]:
import numpy as np
a=np.arange(20).reshape(4,5)
b=np.array([10])
print(a*b)

[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]]


In [4]:
import numpy as np
a=np.arange(8)
print(a)
print(a[1])
print(a[-3])

[0 1 2 3 4 5 6 7]
1
5


In [8]:
import numpy as np
a=np.arange(25).reshape(5,5)
print(a)
print(a[3,4])
print(a[-4,-3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
19
7


In [13]:
import numpy as np
a=np.arange(12).reshape(3,2,2)
print(a)
print()
    
print(a[2,0,1])

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

9


In [14]:
import numpy as np
a=np.arange(12)
print(a)
print(a[2:7])
print(a[:7])
print(a[2:])
print(a[2:7:3])
print(a[::4])
print(a[:-1:2])
print(a[2::3])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[2 3 4 5 6]
[0 1 2 3 4 5 6]
[ 2  3  4  5  6  7  8  9 10 11]
[2 5]
[0 4 8]
[ 0  2  4  6  8 10]
[ 2  5  8 11]


In [16]:
import numpy as np
a=np.arange(24).reshape(4,3,2)
print(a)
print("----------")
print()
print(a[1:3:2,::2])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
----------

[[[ 6  7]
  [10 11]]]


In [1]:
import numpy as np
a=np.arange(24).reshape(4,3,2)
print(a)
print("----------")
print()
print(a[2:3:2,1,1])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
----------

[15]


In [4]:
import numpy as np
a=np.arange(24).reshape(4,3,2)
print(a)
print("-----------")
print()
print(a[slice(1,3,2),::2])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
-----------

[[[ 6  7]
  [10 11]]]


In [17]:
import numpy as np
a=np.arange(100).reshape(10,10)
print(a)
des=np.flip(a,0)
#index=np.array([3,2,1,0])
print("----------------------")
print(des)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
----------------------
[[90 91 92 93 94 95 96 97 98 99]
 [80 81 82 83 84 85 86 87 88 89]
 [70 71 72 73 74 75 76 77 78 79]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]
 [40 41 42 43 44 45 46 47 48 49]
 [30 31 32 33 34 35 36 37 38 39]
 [20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]


In [2]:
import numpy as np
a=np.arange(12).reshape(4,3)
print(a)
b=np.arange(3,-1,-1)
#print(b)
c=np.array([2])
print("-----------------------")
print()
print(a[b,c])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-----------------------

[11  8  5  2]


In [ ]:
import numpy as np